AllCops:
  EnabledByDefault: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Bundler/GemComment:
  Enabled: false

Rails/UniqBeforePluck:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
